name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: git archive --format=zip --output=release.zip $GITHUB_REF
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "system.json,release.zip"
